CONFIG_USB_DEVICE_VID=0x3434
CONFIG_USB_DEVICE_PID=0x0762
CONFIG_BT_DIS_PNP_VID=0x3434
CONFIG_BT_DIS_PNP_PID=0x0762
CONFIG_BT_DIS_FW_REV_STR="v1.3.3"
CONFIG_BT_DIS_HW_REV_STR="v1.0.0"
CONFIG_BT_DIS_SERIAL_NUMBER_STR="SN2024040914230078"
#---------------------------------------------------
# Ativa o protocolo de boot HID por USB
CONFIG_USB_HID_BOOT_PROTOCOL=y

# Força o NKRO / HKRO para o comportamento das teclas
CONFIG_ZMK_HID_REPORT_TYPE_HKRO=y

# Garante o suporte ao subsistema USB nativo do ZMK
CONFIG_ZMK_USB=y

# Desativa o módulo zmk de atualização por bluetooth problemático
CONFIG_ZMK_DFU=n
#---------------------------------------------------
